### ISSUE TITLE
Hope for active development in upstream project

### ISSUE THREAD

**Issue by sk22** [sk22/mastodos#24]
Development on [upstream mastodon-android](https://github.com/mastodon/mastodon-android) has been pretty much dead for almost two months.
I don’t intend to fix upstream bugs by myself (except I happen to really be motivated or I have an idea how to go about some specific bug) because I don’t have enough experience developing and debugging Android apps. As long as I’m using the app myself, though, I don’t want to give up on this fork either.
Not seeing any bugfixes or new features upstream doesn’t exactly motivate me to try implementing additional features. I hope upstream development will be continued soon, and even if not, feel free to contribute to this fork.

**Comment by sirsleon** [comment]
don't give up on it, Mastodos makes using Mastodon on android both a visually pleasing and a feature filled experience that most other clients only offer one or the other of.
