### ISSUE TITLE
Feature: real black mode

### ISSUE THREAD

**Issue by emmatebibyte** [sk22/mastodos#48]
I use an AMOLED screen to reduce the amount of light i take in from my screen. The Mastodon app has a black theme mode, but it only turns some of the app black. I would like it if the theme also applied to the navbar and the header of the app. Would that be something which could be implemented here?

**Comment by sk22** [comment]
definitely, thanks for adding this here! the incompleteness of the upstream "true black mode" has bothered me too

**Comment by emmatebibyte** [comment]
![Screenshot_20221120-160756_Mastodos](https://user-images.githubusercontent.com/58507086/202926261-4254360d-c123-4efd-aa1b-d6a62f924731.png)
Looks awesome, thanks!
