### ISSUE TITLE
App crash log , crash on pressing login

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#52]
Steps to reproduce - After selecting the server and pressing login , the app crashes. This behavior is consistent and replicable.

App Version 1.1.4+fork.42

Android version 12

device - Moto G 5G

Crash log - 
[logcat_11-20-2022_00-58-39.txt](https://github.com/sk22/mastodos/files/10047813/logcat_11-20-2022_00-58-39.txt)

**Comment by sk22** [comment]
not sure if this is related (i hope it is!), but i'll publish a new version in a minute

**Comment by sk22** [comment]
can you try again now?

**Comment by karano-techie** [comment]
Just tried , but same result.

**Comment by sk22** [comment]
mmh :/ does it work on the official app?

**Comment by karano-techie** [comment]
yeah ,official app is working fine. Though i noticed some ocassional crashes in that too

**Comment by sk22** [comment]
hah yeah, the official app is also months old (last released version is from july!)
i think i can reproduce your bug now. you can, in the meantime, type in the address of your instance (instead of selecting it from the list) and pressing enter

**Comment by sk22** [comment]
turns out this is actually an upstream issue (that is, when i build the app myself from the latest source code)

**Comment by karano-techie** [comment]
Ohh , thanks . Looks like it might be. Donno whats the upstream development status.
Anyway your workaround works for now !!

**Comment by sk22** [comment]
Created an issue for it here: mastodon#386
Glad to hear the workaround worked! :D

**Comment by karano-techie** [comment]
Also quick question . What about playstore release. Would love to contribute to the app , and spread a word.

**Comment by sk22** [comment]
maybe at some point, but i know absolutely nothing about all that. i'll prioritize f-droid tho!

**Comment by karano-techie** [comment]
@sk22  Most people are accustomed to install app through the playstore. And i am trying to refer this app to people , but most of them asked why its not on playstore.
I know getting app on the playstore doesn't assure safety of the app.
But as majority are unaware of fdroid and github , its a good place to distribute the app.
I think i know the process of publishing apps to playstore.
