### ISSUE TITLE
Profile options menu not visble in light theme

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#54]
in light theme mode , after clicking on the 3 dot menu on somebodys profile ,
the options aren't visible as the text is also light
 refer screenshot.
 ,![Screenshot_20221120-023909-501.png](https://user-images.githubusercontent.com/93819980/202871742-d92339f8-6ff8-4422-be18-3cb3ee517daf.png)

**Comment by sk22** [comment]
ugh shit. thanks!
