### ISSUE TITLE
Invisible Menu Entries

### ISSUE THREAD

**Issue by bama35453** [sk22/mastodos#55]
On the profile tab when tapping on the three dots in the upper right corner a menu will open.
It contains three entries:
- Share profile of account owner
- Lists of accout owner
- Favorite posts

These entries are unreadable when using the light theme since the text color is white on a slightly grayish background.
The white text is ok for the dark mode, but it should be black in light mode.

**Comment by sk22** [comment]
yeah, i messed up the true black theme improvements - will release a fix asap!
