### ISSUE TITLE
Searching with account url crashes app

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#61]
Steps to reproduce -
If we enter a profile url in the search bar , the app crashes altogether. The crash is seen most of the times. It also might be an upstream bug , but can't confirm.

App version 1.1.4+fork.45
Android version 12

Crash log files reproducing similar crashes -
[logcat_11-20-2022_11-47-20.txt](https://github.com/sk22/mastodos/files/10049264/logcat_11-20-2022_11-47-20.txt)
[logcat_11-20-2022_11-55-07.txt](https://github.com/sk22/mastodos/files/10049265/logcat_11-20-2022_11-55-07.txt)
[logcat_11-20-2022_12-14-41.txt](https://github.com/sk22/mastodos/files/10049266/logcat_11-20-2022_12-14-41.txt)

**Comment by sk22** [comment]
probably because of this upstream bug: https://github.com/mastodon/mastodon-android/issues/383

**Comment by sk22** [comment]
in my experience, this bug didn't occur when the recent searches were empty - if possible, could you test that?

**Comment by karano-techie** [comment]
> in my experience, this bug didn't occur when the recent searches were empty - if possible, could you test that?

Yeah , on clearing out the recent searches the crash doesn't seem to occur.  i have to make couple os searches first then insert the url to make it crash

**Comment by sk22** [comment]
should be fixed with upcoming release (grishka's appkit, which the official app depends on, was updated to fix this!)
