### ISSUE TITLE
Add ability to see profile of user reblogging posts

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#62]
Feature request - (searched for prior issues/requests for this but found none)
**Add ability to see profile of user boosting posts** - If it were possible to directly visit a users profile by clicking on the space which says " xyz reblogged" on top of a post in home timeline would be very useful in case we want to quickly unfollow or mute the person who reblogged the post rather than currently having to go to search bar and entering their name.

**Comment by sk22** [comment]
thanks for the request! should be rather easy to implement :)
