### ISSUE TITLE
Can't authorize the app

### ISSUE THREAD

**Issue by stemy2** [sk22/mastodos#64]
Hello,

I'd like to authorize the app, but when i'm clicking on "authorize", it loads and...redirects to the same page, where i'm asked to authorize the app.

**Comment by sk22** [comment]
hm. does that also occur with the official app? if you have both installed, maybe you mistakenly (or it happened automatically) opened the other app when pressing "authenticate"? in this case, maybe uninstalling the official app first might help

**Comment by stemy2** [comment]
The official app is not installed.

**Comment by sk22** [comment]
can you just try whether it works on the official app?

**Comment by sk22** [comment]
i could imagine your browser somehow messing up the authorization redirect, but in this case, the official app should also be affected as i didn't really change any of the code that handles this

**Comment by stemy2** [comment]
Strangely, having both app installed solved my problem. At the validation, it asked me wich app i wanted to use, and after i selected the right one (depending if i was using the official or the fork), the validation worked fine.

**Comment by sk22** [comment]
huh, weird. tbh, this kind of processes always scare me a bit (because i never know if it's gonna work), but i'm glad it solved your problem!
closing this for now - if it comes up again (and it turns out it's not an issue with the upstream app), we can re-open the issue.
