### ISSUE TITLE
UI: What color should the default for non-existent headers be?

### ISSUE THREAD

**Issue by sk22** [sk22/mastodos#66]
Originally, it was a shade of gray… which was definitely too bright for the true black mode, so I changed it to the window background color. I've found that this looks especially odd when looking at a profile without header image in light mode. In case anyone has any hard opinions about this, please let me know!

**Comment by karano-techie** [comment]
mmh....in the light mode it does appear to be little bit off . I would perfer it to be grey to keep it more standard. 
The grey part may actually inform people in dark mode that the header of a profile is not set.

**Comment by sk22** [comment]
hm, fair point
