### ISSUE TITLE
App crash when push service missing.

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#71]
My app has been randomly crashing on any app screen. I suspect the reason for this (going by the crash log) is the lack of push services on my device.
For certain purposes i had removed google push services from my device. I am fine with not receiving push notifications.
But due to lack of push service its making the app to crash.
( This bug might be upstream too)
Though i am not able to layout sepcific steps to reproduce this issue. The crash is occasional in nature.
Expected behavior - App shouldn't crash if no push service is detected.

![logcat_11-21-2022_00-04-34.txt](https://github.com/sk22/mastodos/files/10050437/logcat_11-21-2022_00-04-34.txt)
(refer errors at the last in log for this specific issue)

**Comment by sk22** [comment]
closing and hoping for an upstream bugfix
