### ISSUE TITLE
APK at the last release is a debug build

### ISSUE THREAD

**Issue by IzzySoft** [sk22/mastodos#72]
Just to let you know: the APK attached at your latest release (`versionCode: 46`) is compiled for debug. Not sure if that was intended (e.g. to allow data backup on Android 13+); shouldn't that rather be a release build?

**Comment by karano-techie** [comment]
Yeah i think you are right. This is why i think after updating it logged me out and cleared old data.

**Comment by sk22** [comment]
ahh true, i probably shouldn't have changed the "debuggable" flag for the release build. just wanted to ensure the stack traces aren't obfuscated (so things are easier to debug when people send me crash logs), but the app doesn't have to be "debuggable" for that. will change that again in the next release, sorry for the inconvenience!

**Comment by IzzySoft** [comment]
No prob, just wanted you to be aware. When the next release is fetched and the flag is gone, my updater will send me a notice to remove the corresponding AntiFeature as well, so that will solve (semi-)automatically. Thanks!
