### ISSUE TITLE
Make publish button rounder and smaller

### ISSUE THREAD

**Issue by karano-techie** [sk22/mastodos#74]
The publish button (see attached image) doesn't look very proportional to the rest of the screen. Also better aesthetic choice would be to make it round than a sqaure. (refer image 2)
A more modified icon to consider is (image 3 with rounded shape)
 ![Screenshot_20221121-143831-556.png](https://user-images.githubusercontent.com/93819980/203011729-a880a876-d3a1-4eeb-9956-b5499fbabc1a.png)
![Screenshot_20221121-143949-678.png](https://user-images.githubusercontent.com/93819980/203011773-9c5e1f15-4a19-42cd-bc37-896bbe2e967c.png)
![Screenshot_20221121-144630-685.png](https://user-images.githubusercontent.com/93819980/203012098-38d57b19-08f8-4732-94d2-5857ff25fa95.png)

**Comment by sk22** [comment]
yeah, no, i don't plan to do this. should it be something that many people want, we can re-open the issue, but closing for now.
