### ISSUE TITLE
Updater downloads upstream APK instead of Mastodos

### ISSUE THREAD

**Issue by KibSquib48** [sk22/mastodos#79]
I just tried upgrading from v1.1.4+fork.46 to v1.1.4+fork.47 and it downloaded the upstream APK instead of Mastodos

**Comment by sk22** [comment]
uhhh what??? ok hold on

**Comment by sk22** [comment]
okay shit, you're right – i deleted the upstream version from the release for now!

**Comment by sk22** [comment]
okay, fixed this and released a new version!
